name:                
version:             0.1.0.0
license:             GPL3
author:              "morj"
maintainer:          "contact@morj.com"
synopsis:            Does stuff

executables:
  app-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Wcompat
    dependencies:
    - base
