name:                
version:             0.1.0.0
license:             BSD3
author:              "d86leader"
maintainer:          "d86leader@mail.com"
synopsis:            Does stuff

executables:
  app-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Wcompat
    dependencies:
    - base
